apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  containers:
    - name: simple-app
      image: styagi935/simple-app:tagVersion
      ports:
        - containerPort: 8080
