apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  type: LoadBalancer
  selector:
    app: simple-app
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
