replicaCount: 2

image:
  name: firstimg
  repository: docker.io/signin/helm
  tag: "latest"
  pullPolicy: IfNotPresent


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

container:
  port: 8080

service:
  protocol: TCP
  type: LoadBalancer
  port: 8080
